### ISSUE TITLE
Extra time and Penalties

### ISSUE THREAD

**Issue by dbecker801** [j0k3r/worldcup-slack-bot#13]
Thank you to Spain and Russia for giving us a test case.

From looking at the JSON from the FIFA API it looks like extra time could get mapped as such by the bot:

`const PERIOD_1ST_ET = 7;`
`const PERIOD_2ND_ET = 9;`

**Comment by j0k3r** [comment]
Extra time is done in https://github.com/j0k3r/worldcup-slack-bot/pull/14
Penalties still need to be handled
