### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by invinciberry** [j0k3r/worldcup-slack-bot#18]
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/jason/projects/worldcup-slack-bot/worldCupNotifier.php on line 405

**Comment by j0k3r** [comment]
Fixed https://github.com/j0k3r/worldcup-slack-bot/commit/ec3f6d12a6e6cf53487cde2ff3ee822c8c5bcb35
